site_name: Concourse Tutorial by Stark & Wayne
pages:
  - Basics:
    - Introduction: index.md
    - Hello World: basics/01-task-hello-world.md
    - Task Inputs: basics/02-task-inputs.md
    - Task Scripts: basics/03-task-scripts.md
    - Basic Pipeline: basics/04-basic-pipeline.md
    - Hello World Pipeline: basics/05-pipeline-task-hello-world.md
    - Watch Job Output: basics/06-watch-job-output.md
    - Trigger Jobs with API: basics/07-trigger-jobs-with-api.md
    - Triggers: basics/08-triggers.md
    - Destroying Pipelines: basics/09-destroy-pipelines.md
    - Job Inputs: basics/10-job-inputs.md
    - Outputs to Inputs: basics/11-task-outputs-to-inputs.md
    - Publishing Outputs: basics/12-publishing-outputs.md
    - Pipeline Jobs: basics/13-pipeline-jobs.md
    - Parameters: basics/14-parameters.md
    - Secrets with Credentials Manager: basics/15-secret-parameters.md
  - Miscellaneous:
    - Introduction: miscellaneous/index.md
    - Run Tests Before Deploy: miscellaneous/run-tests-before-deploy.md
    - Create and Use Docker Images: miscellaneous/docker-images.md
    - Versions and Build Numbers: miscellaneous/versions-and-buildnumbers.md
    - GitHub Release Input: miscellaneous/github-release-input.md
    - Slack Notifications: miscellaneous/slack-notifications.md

theme:
  name: 'material'
  custom_dir: 'theme-overrides'
  palette:
    primary: 'orange'
    accent: 'amber'
  feature:
    tabs: true

  font:
    text: 'Bitter' # https://fonts.google.com/specimen/Bitter
    code: 'Ubuntu Mono'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences
  - toc(permalink=true)

repo_name: 'help fix the tutorials'
repo_url: 'https://github.com/starkandwayne/concourse-tutorial'
edit_uri: edit/develop/docs/
extra_css: [print.css]
