---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: notify
  type: slack-notification
  source:
    url: ((slack-webhook))
- name: tutorial
  type: git
  source:
    uri: https://github.com/starkandwayne/concourse-tutorial.git
    branch: develop

jobs:
- name: test
  public: true
  serial: true
  plan:
  - do:
    - get: tutorial
      trigger: true
    - task: test-sometimes-works
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: busybox}
        inputs:
        - name: tutorial
        run:
          path: tutorial/tutorials/miscellaneous/slack_notifications/test-sometimes-works.sh
    - put: notify
      params:
        channel:  ((slack-channel))
        username: ((slack-username))
        icon_url: ((slack-icon))
        text:    "'test' job succeeded"
    on_failure:
      put: notify
      params:
        channel:  ((slack-channel))
        username: ((slack-username))
        icon_url: ((slack-icon))
        text:    "'test' job failed"
