---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/starkandwayne/concourse-tutorial.git
    branch: develop

jobs:
- name: job-pass-files
  public: true
  plan:
  - get: resource-tutorial
  - task: create-some-files
    file: resource-tutorial/tutorials/basic/task-outputs-to-inputs/create_some_files.yml
  - task: show-some-files
    file: resource-tutorial/tutorials/basic/task-outputs-to-inputs/show_files.yml
