meta:
  name:    concourse-tutorial
  team:    concourse-tutorial
  # fly -t ohio-ct login -c https://ci-ohio.starkandwayne.com -n concourse-tutorial
  target:  ohio-ct
  url:     https://ci-ohio.starkandwayne.com

  cf:
    api:              ((!cf-api))
    skip_cert_check:  false
    username:         ((!cf-username))
    password:         ((!cf-password))
    organization:     ((!cf-organization))
    space:            ((!cf-space))

  github:
    owner: starkandwayne
    repo: concourse-tutorial
    private_key:  ((!github-private-key))
    access_token: ((!github-access-token))

  concourse:
    url:      ((!concourse_url))
    username: ((!concourse_username))
    password: ((!concourse_password))
    ca_cert:  ""

  credhub:
    url:      ((!credhub_url))
    username: credhub-cli
    password: ((!credhub_password))
    ca_cert:  ((!credhub_ca_cert))
